### ISSUE TITLE
Link to the public meeting notes looks outdated

### ISSUE THREAD

**Issue by jtpio** [jupyter/accessibility#105]
The current public notes point to an issue in the `jupyterlab/team-compass` that has been closed:

https://jupyter-accessibility.readthedocs.io/en/restructure/README.html#join-our-jupyterlab-accessibility-meetings

![image](https://user-images.githubusercontent.com/591645/182856328-420be05a-a139-4c7b-90da-2ca2292071be.png)

Currently pointing to https://github.com/jupyterlab/team-compass/issues/98

**Comment by jtpio** [comment]
> Currently pointing to [jupyterlab/team-compass#98](https://github.com/jupyterlab/team-compass/issues/98)

According to the linked issue it should have been fixed in https://github.com/jupyter/accessibility/issues/75 and https://github.com/jupyter/accessibility/pull/78

**Comment by jtpio** [comment]
So maybe the fix for now would be to change the link to the Jupyter Accessibility website so it points to https://jupyter-accessibility.readthedocs.io/en/latest/README.html

And updated the link in the README as well: https://github.com/jupyter/accessibility#handshake-join-our-jupyterlab-accessibility-meetings

**Comment by jtpio** [comment]
So probably something is broken with the docs right now as https://jupyter-accessibility.readthedocs.io/en/latest/community/meeting-minutes/jupyterlab-accessibility-meetings/index.rst is giving a 404.

And the latest builds failed: https://readthedocs.org/projects/jupyter-accessibility/builds/

![image](https://user-images.githubusercontent.com/591645/182858770-df38c147-018c-4053-a85c-bc5a7f6f0a40.png)

**Comment by trallard** [comment]
Thanks for flagging this up @jtpio  I am currently giving this repo and docs a big overhaul as we have a number of outdated items. 
Thanks for your patience in the meantime
