### ISSUE TITLE
Previous meeting notes archive is not available

### ISSUE THREAD

**Issue by jooyoungseo** [jupyter/accessibility#113]
Please fix the link. It's not available: https://github.dev/jupyter/accessibility/blob/cfc0b49c1410de064a10196d5420fb174b818f62/README.md#L43-L44

**Comment by isabela-pf** [comment]
Thanks for catching this @jooyoungseo! I think this is a result of #106 and that it requires an updated link to reflect the restructure. I'll try to get that fixed as soon as we can.
