### ISSUE TITLE
Looking for another person to spearhead the Jupyter accessibility workshop

### ISSUE THREAD

**Issue by choldgraf** [jupyter/accessibility#13]
Hey all - this is a difficult message for me to write, but I think it's best if I step down from being the "point person" in organizing the Jupyter Accessibility workshop. I am happy to continue assisting with planning etc, but don't have the bandwidth to be the one responsible for making it all happen because I am expecting a baby girl in early August (our first, so who knows what'll happen!).

How can we gracefully hand off "ownership" of this event in a way that ensures that it still happens, and that responsibility lands on other people in an equitable way? I am happy to work with folks to help plan things, meet to discuss ideas, etc. I just can't be the one who needs to worry about how to make this happen.

What do folks think? I've got about another 2 weeks of reliable work in me before I may have a kid, so happy to put in time to handing this off or moving things forward before then.

---

Background for those who weren't involved in the original planning:

We have a Bloomberg community grant to fund a workshop dedicated towards improving accessibility in the Jupyter ecosystem (probably Jupyter Lab in particular). This was originally going to be in March, and then COVID happened and we had to post-pone. We hoped that things would get better and we'd be able to have it this summer, but they didn't. Our latest conversations were around making this a remote meeting, and post-poning any kind of in-person meeting until the world heals itself a bit.

(see #11 for conversations around this)

**Comment by clapierre** [comment]
Normally I would do this as part of DIAGRAM since we helped organize the original Hackathon on Jupyter, but we are scrambling to get everything done before the DIAGRAM Center+ award from OSEP ends at the end of August this year and we don't have any additional funding.  I will keep an eye on this but am also unable to lead in the organization of this accessibility workshop at this time.

**Comment by trallard** [comment]
Hey folks. I would be happy to take on this workshop. That said it would be great if there were at least two co-organisers.

@choldgraf would it be possible to schedule a call before you are unavailable for handover and the such?

**Comment by choldgraf** [comment]
absolutely - I'm happy to do whatever I can to move things forward. I just can't be the one on which the process bottlenecks. (and I might go dark for several weeks starting sometime in August)

**Comment by choldgraf** [comment]
Updating with this message, then I'll close this and move conversation back to  

---

Hey all - I just had a meeting @trallard , and we came up with the following plan. 

- Attach an accessibility sprint / workshop to either [**JupyterCon**](https://jupytercon.com/) or [**PyData Global**](https://global.pydata.org/).
  - Ensure that we have enough availability from the folks in this thread that we can make meaningful progress towards auditing / roadmapping Jupyter interface accessibility
  - We could also use this to get participation from other interested parties that attend those conferences
- @trallard will lead the organization of this effort. She is going to explore either baking this in to one of the sessions as JupyterCon or proposing it as a satellite event.
- I will help out however I can, whenever I can poke my head out of the fog of new baby.

If you have any thoughts or ideas here, please chime in over in #11
