### ISSUE TITLE
Wrong urls used in the Accessibility documentation to access accessibility issues in JupyterHub and JupyterLab

### ISSUE THREAD

**Issue by bl-aire** [jupyter/accessibility#130]
On checking the Accessibility documentation, I noticed wrong urls were used. Clicking on:

- JupyterHub accessibility issues opens Notebook's accessibility issues
- JuputerLab's accessibility issues opens JupyterHub's accessibility issues

I am attaching pictures to show what I mean. And, If approved, I would love to fix it. 

<img width="1280" alt="Screenshot 2023-06-01 at 22 08 56" src="https://github.com/jupyter/accessibility/assets/84882370/3b28e9ca-2d66-4821-a394-3876243ff62b">

<img width="1280" alt="Screenshot 2023-06-01 at 22 14 49" src="https://github.com/jupyter/accessibility/assets/84882370/eb6a116a-ca86-433b-8f5c-dd8319b2f886">

**Comment by trallard** [comment]
Hey @bl-aire thanks for opening this issue. Please feel free to send a PR to fix this ☺️
