### ISSUE TITLE
capturing the accessibility meeting minutes in the repo

### ISSUE THREAD

**Issue by tonyfast** [jupyter/accessibility#132]
we haven't captured meeting notes in the repo all year. is there anyone that has the time and focus to go through the back log of notes that have not made it into the repo? 

we stopped adding notes on 9/2022 

the notes are still running the same https://hackmd.io/WnaWXboXSiGoqWvev_fAvA

#119 has complicated the process a bit i feel.

**Comment by trallard** [comment]
I can add the notes to the repo - we have a big backlog now

**Comment by tonyfast** [comment]
that would be really helpful
