### ISSUE TITLE
Bi-weekly meeting time has been updated

### ISSUE THREAD

**Issue by afshin** [jupyter/accessibility#134]
Hi everyone!

At our last meeting on 26 July 2023, we decided to ask the Jupyter Server team if we could move our call to a slightly better time slot for a plurality of the people who have recently been joining our calls.

- Our new time slot is: **every other week on Thursdays at 9AM Pacific time** beginning with our next call on **10 August 2023**. See you then!
- I created a GitHub group (@jupyter/accessibility-council) and invited the members of the Jupyter Accessibility Council (all the names from our Google Group, assuming that the group membership there is correct).
- I updated the [Jupyter Community calendar](https://discourse.jupyter.org/t/jupyter-community-calendar/2485) to reflect our new meeting time.

**Comment by trallard** [comment]
Thanks @afshin 🙏 since you are fishing all the places where this needs fixing could you send a PR here to update the new day and time?

**Comment by afshin** [comment]
@trallard: https://github.com/jupyter/accessibility/pull/135 🤓

**Comment by bl-aire** [comment]
Hello,

I just want to be sure. So its still bi-weekly but has been changed to Thursday?

**Comment by tonyfast** [comment]
Yes. Still biweekly. Now we meet Thursday’s at 9am PST.

**Comment by bl-aire** [comment]
> Yes. Still biweekly. Now we meet Thursday’s at 9am PST. 

Okay. Thank you

**Comment by tonyfast** [comment]
closed by #135
