### ISSUE TITLE
Proposal: Set a one-year term for the Accessibility project's SSC representative

### ISSUE THREAD

**Issue by isabela-pf** [jupyter/accessibility#138]
## Background

In the current Jupyter governance model, [Jupyter Accessibility is a software subproject](https://jupyter.org/governance/list_of_subprojects.html). As a software subproject, we elect a council member to represent us on the Jupyter Software Steering Council (SSC). At the time of writing, I am that representative. 

While we have [a process for this election](https://jupyter.org/governance/decision_making.html), the accessibility project has not previously made a formal decision related to term length or representative election timelines. The [Jupyter Software Subproject documentation](https://jupyter.org/governance/software_subprojects.html) currently leaves this decision up to the software subprojects themselves. 

## Proposal

**I propose we set the term length for accessibility subproject SSC representatives to be a year.** This would require annual elections. I am not proposing any caps on the number of terms or consecutive terms at this time.

I'd like to bring this to a vote, but I want to make sure I leave time for discussion outside meeting times as well. I will follow up in a week to see what next steps are relevant. 

## Actions needed

- Discuss the proposal as desired in this issue (open to council members and the public)
- Bring up amendments to the proposal (open to the council members and the public)
- Comment if you are interested in a vote (at least one council member other than me needs to also want this to be a vote in order to start one; if no one else is interested that also makes our decision)

Thank you for your time and thoughts!

cc: @jupyter/accessibility-council

**Comment by fcollonval** [comment]
Thanks @isabela-pf I support this proposal. Lots of Jupyter projects have done so. And this is a great way for members to increase their involvement if they are interested.

**Comment by tonyfast** [comment]
i think that this makes sense. thanks for raising the issue. 

the [accessibility to burnout pipeline](https://www.deque.com/axe-con/wp-content/uploads/2022/12/The-Accessibility-to-Burnout-Pipeline_a11y.pdf) is real. terms would allows members to check if they are properly resourced and supported to continue serving these roles.

**Comment by trallard** [comment]
I am +1 on this proposal

**Comment by isabela-pf** [comment]
Thank you all for commenting! 

Given that there hasn't been any reason mentioned to not hold a vote and that voting will be an expression of opinion anyways, I'll set up a vote. I will report the results back on this issue and close it once the vote is completed.

**Comment by isabela-pf** [comment]
The voting period for this proposal has closed!

* Yes: 9 votes
* No: 0 votes
* Abstain: 0 votes.

With a voting body of 10 council members, the quorum of 50% is met and the proposal passes.

Thank you all for your time. I will be looking into what document/documentation changes need to be made to update this change then.
