### ISSUE TITLE
Add members of Accessibility Council to our `team-compass`

### ISSUE THREAD

**Issue by afshin** [jupyter/accessibility#143]
I couldn't find a list of the up-to-date members of the Jupyter Accessibility Council and our SSC representative. I think we have a canonical list somewhere, right? Let's have it on the published page.

**Comment by tonyfast** [comment]
i'm not sure where the list is either. i think @gabalafou has been dealing with some of these organizational things being the SSC rep. maybe he knows if there is a good list somewhere amongst the pages they could be scattered in.

**Comment by isabela-pf** [comment]
Canonical list is on the mailing list and, to my knowledge, nowhere else as the moment. I can make a PR with a markdown file that lists it and people can move it wherever they want in the docs. I will mention it here when I have it up.

**Comment by trallard** [comment]
Thanks @isabela-pf I went ahead and merged the PR so will close this issue.
