### ISSUE TITLE
(Accesibility council) Vote to fold accessibility meeting into frontends weekly meeting

### ISSUE THREAD

**Issue by ohrely** [jupyter/accessibility#149]
Discussed in #148 and https://github.com/jupyterlab/frontends-team-compass/issues/252.  Frontends council vote at https://github.com/jupyterlab/frontends-team-compass/issues/254.

## Proposal
Merge accessibility meetings into frontends meetings:

- Rebrand the existing weekly Wednesday Jupyter Frontends meeting to a Jupyter Frontends and Accessibility meeting.
- Remove the existing alternating Thursdays accessibility meeting from the [Jupyter Community Calendar](https://discourse.jupyter.org/t/jupyter-community-calendar/2485).
- Advertise that accessibility topics are welcome in all of the combined meetings but members of the accessibility subproject will make a particular effort to attend the first meeting of each calendar month.

Per the [Jupyter decision-making guide](https://github.com/jupyter/governance/blob/main/decision_making.md), "After the proposal is seconded by another member of the council, members have seven days to vote."

## Votes

- @trallard
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @ajbozarth
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @fcollonval
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @marthacryan
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @afshin
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @ohrely
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @gabalafou
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @krassowski
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @isabela-pf
  - [ ] Yes
  - [x] No
  - [ ] Abstain

**Comment by ohrely** [comment]
I don't have permission to add a "vote" label to this, would appreciate if someone could!

**Comment by fcollonval** [comment]
I can't vote due to missing rights. But my vote is for `yes`

**Comment by afshin** [comment]
I think you should have permission now, @fcollonval!

**Comment by krassowski** [comment]
I do not have a permission to vote. I think I would vote "yes" with a caveat that having a quarterly or half a year dedicated accessibility-only meeting could be a good addition to this proposal.

**Comment by trallard** [comment]
Agree, been too busy to sit down and write thoughts. 
But I would like to continue to find opportunities or create space to discuss accessibility within Jupyter as a whole (vs solely in the context of Jupyter frontend).

**Comment by ohrely** [comment]
> I do not have a permission to vote.

Voted "yes" for you, hope that's okay @krassowski.  I think @trallard and @afshin have the power to add you to the [accessibility team](https://github.com/orgs/jupyter/teams/accessibility) for future votes.

> But I would like to continue to find opportunities or create space to discuss accessibility within Jupyter as a whole (vs solely in the context of Jupyter frontend).

My understanding/expectation while pushing for this meeting merge has been that all Jupyter accessibility topics, frontends-related or not, will be fair game at the Wednesday calls (esp. during the 1st meeting of the month).  If the amount of meeting time dedicated to frontends-unrelated accessibility topics becomes a burden, we can reassess the wisdom of merging the two meetings.

> I think I would vote "yes" with a caveat that having a quarterly or half a year dedicated accessibility-only meeting could be a good addition to this proposal.

I like the idea of an occasional "Jupyter Accessibility Summit" to discuss topics that don't tend to come up in weekly calls (big direction decisions, council membership maintenance, etc.)

**Comment by trallard** [comment]
I am +1 on having a summit/separate call whatever it is. 

I am very unlikely to make it to the frontends call as I have hard scheduling conflicts at the time/day these take place so having other alternatives to discuss meta accessibility topics would be good for me and potentially others.

**Comment by ohrely** [comment]
Closing this issue to mark vote completion as we are at 100% voted.  Final tally: 8 yes, 1 no.
