### ISSUE TITLE
Store accessibility meeting notes in this repo

### ISSUE THREAD

**Issue by isabela-pf** [jupyter/accessibility#16]
The JupyterLab community has been having JupyterLab accessibility meetings for a few months now and have been storing minutes under [jupyterlab/team-compass #98](https://github.com/jupyterlab/team-compass/issues/98). This has resulted in a lot of notes that describe both our progress working on JupyterLab and things we’ve learned along the way that are not JupyterLab specific. I don’t think an single issue is a sustainable or easy to navigate for notes long term, so I wanted to propose storing meeting minutes in this repo. 

While I am asking what people think about putting those specific minutes in this repo, I also think other accessibility-related meeting notes should live here too (like if we are able to successfully resurrect the accessibility workshop :eyes:). This would provide a resource for people currently working on accessibility in the Jupyter ecosystem and give us a centralized place to send others looking for resources or information on what we are doing.

For an example of what I’m thinking, I’m imagining something of a cross between the [jupyter/surveys](https://github.com/jupyter/surveys) repo and [nteract/meeting-minutes](https://github.com/nteract/meeting-minutes). I think there should be a folder labeling what set of meetings these notes are from and a list of dated markdown files for all the notes.

If there’s not any comment on this by the end of day Monday February 15 (PST), I’ll put in a PR to add the JupyterLab accessibility meeting minutes and we can chat more then.

**Comment by willingc** [comment]
@isabela-pf Thanks for taking the initiative on this.

**Comment by willingc** [comment]
See https://github.com/jupyter/accessibility/pull/17#issuecomment-785287752 and related posts on ongoing workflow suggestions. cc/ @goanpeca @jasongrout

**Comment by jasongrout** [comment]
On behalf of the steering council: Members of the @jupyter/accessibility team (including you, @isabela-pf) should now have merge rights to this repo. Thank you again for the great work you are doing in helping Jupyter be more accessible.

**Comment by meagdoh** [comment]
Hi there, it’s great to see updates here. I lead experience design efforts at [All of Us Research Program](researchallofus.org) where we integrate with Jupyter notebooks.  Is this the best place to watch for updates? Are there other ways for people to get involved? Thanks!

**Comment by willingc** [comment]
Thank you @jasongrout for taking the lead on this for the Steering Council. :smile: Looking forward to the work coming out of this effort.

**Comment by isabela-pf** [comment]
Hi @meagdoh! I think this is the best place to watch to get an overview of what's happening with accessibility work around Jupyter. Most of the current effort I'm aware of is for JupyterLab and its building blocks, so while we are posting notes here you can find more specific plans and progress on the [JupyterLab repo with the accessibility tag](https://github.com/jupyterlab/jupyterlab/issues?q=is%3Aissue+label%3Atag%3AAccessibility+) which is also summarized in this [github project](https://github.com/orgs/jupyterlab/projects/1).

And yes, anyone is welcome to get involved in this work! You can collaborate with anything listed above or contribute your own expertise if there's an area you think we are missing. Probably the best way to get up to speed is to join one of our JupyterLab accessibility meetings and hear what the team is working on and where we missing support. Our next meeting is Wednesday, March 11 at 10:15am PST and you can join any of these meetings from the [Jupyter community calendar](https://jupyter.readthedocs.io/en/latest/community/content-community.html#jupyter-community-meetings). Hope to meet you soon!

**Comment by isabela-pf** [comment]
Since we've started storing meeting notes in this repo, I'm going to close this issue. We can always reopen or start a new issue for further discussion.
