### ISSUE TITLE
use this repository to host a full development testing environment

### ISSUE THREAD

**Issue by tonyfast** [jupyter/accessibility#18]
Our immediate needs are a simple system to test concurrent changes in both lumino and jupyterlab code. we can likely use this repo as a bridge.

the immediate needs are:
* a `postBuild` that links to a certain a reference to git on jupyterlab and lumino.
   * changes to lumino will have to be built and linked.
   * jupyterlab dev build
* a `START` files that customizes the way the application is launched.

later we can think about:
* adding common/popular extensions
* building core documentation for auditting

the binder should by default be a development build of jupyter lab and lumino so that folks can audit and test directly from the build we design.

some challenges are a simple way to make a new branch that connects different versions of repos. it would be best if folks didn't have to make a commit, then again a manifest of repos and references could be useful for extending this idea.

**Comment by isabela-pf** [comment]
This work was referenced in our last JupyterLab accessibility meeting. Some people asked if this was ready to use and if there was any documentation for it, so I'm passing along the questions here.

**Comment by trallard** [comment]
This will be superseded by #86 - so will mark as obsolete for now and can then reevaluate as we move forward with the work

**Comment by trallard** [comment]
Closing as we decided to move tooling out of this repo - tracking in https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/144
