### ISSUE TITLE
mar 3 2021 working meeting

### ISSUE THREAD

**Issue by tonyfast** [jupyter/accessibility#23]
Welcome to our first hands on accessibility community meeting. These events are for learning and sharing knowledge about accessibility within our diverse, growing community. On alternate week,s @isabela-pf will run our project meetings.

> if you are seeing this issue, please react to issue with each thing you want to participate in, you should choose more than 1.

- :heart: i'm happy to be here!
- :eyes: i want learn about accessibility by reviewing existing issues and pr's
  - fall down the [9399](https://github.com/jupyterlab/jupyterlab/issues/9399 "the necessary changes for accesibility") :rabbit: hole
- :smile: i want to work on the [readme](readme.md) with @isabela-pf _only requiring markdown knowledge_
  - add badges to gitter, google calendar, discourse, other meetings folks can go to, edit the contents of the readme
- :rocket: i want to work on tasks that _only requiring css knowledge_
  - _are there some css specific issues somewhere?_
- :tada: setup jupyterlab/lumino dev environment only requiring conda & :crying_cat_face: 

we'll split into groups and ~~work/learn~~**have fun** together.

please use this issue to add meeting notes by adding comments.

> links > substance > style

**Comment by tonyfast** [comment]
[Web Content Accessibility Guidelines](https://en.wikipedia.org/wiki/Web_Content_Accessibility_Guidelines#WCAG_1.0)

**Comment by saulshanabrook** [comment]
Questions:

*   What is CSS?
    *   @jasongrout said, "CSS lets you control the styling of anything on a webpage, like what colors things are, what padding and margins things have, fonts, etc."
    *   Introduction: [https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics)
*   What is accessibility?
    *   There are WCAG guidelines. They have standards for accessibility: [https://en.wikipedia.org/wiki/Web_Content_Accessibility_Guidelines#WCAG_1.0](https://en.wikipedia.org/wiki/Web_Content_Accessibility_Guidelines#WCAG_1.0)
        *   @isabela-pf this can lead to legal guidelines
    *   One of the basic things is having "alt text" for images to talk. https://ahrefs.com/blog/wp-content/uploads/2020/03/00-alt-text.png

**Comment by bollwyvl** [comment]
here is [another nice comic](https://comica11y.humaan.com/ "the link to a web comic").

**Comment by bollwyvl** [comment]
for your perusal:

- this is some work we started on `pydata-sphinx-theme`: [PR](https://github.com/pydata/pydata-sphinx-theme/pull/294 "Add pa11y testing and reporting"), with the goals of:
  - establish a baseline of rules the project
    -   rule sets, roadmaps for things _known_ to be improved
  - be able to do "best effort" testing of static websites to on a local computer and in continuous integration
    - capture the results as annotated screenshots, HTML, machine-readable JSON
  - be open source :tada:

**Comment by isabela-pf** [comment]
Responding to 
> are there some css specific issues somewhere?
[#8832](https://github.com/jupyterlab/jupyterlab/issues/8832) is a work in progress, but will be mostly if not all CSS.
[#9682](https://github.com/jupyterlab/jupyterlab/issues/9682) is in HTML, but requires a similar level of knowledge.

Flow chart for different types of alt text and how to use it (@melissawm): https://www.w3.org/WAI/tutorials/images/decision-tree/
Their overview for alt text: https://www.w3.org/WAI/alt/

**Comment by MarsBarLee** [comment]
**Example of the importance of using the correct HTML tags for screen readers.**
Labeling a title 'How to make cookies' with the Heading 1 tag,
< h1 > and labeling 'Ingredients' with Heading 2 tag, < h2 >."

The screen header will read out 'Header 1: How to make cookies' and 'Header 2: Ingredients'.

**Less accessible version:**
'How to make cookies' and ingredients with no heading tags. Instead, text is only visually made bigger and bolder.

The screen header will read out 'How to make cookies. Ingredients'. Less clear.

**Comment by manfromjupyter** [comment]
^ Just adding onto to @isabela-pf's comment regarding CSS specific work. There's also the low vision (same as mobile/tablet responsiveness stuff), which will be all mostly CSS and a small amount of HTML (in the form of Typescript returns) fixes, but I don't think I've created exacts on this yet but can next week. I definitely feel the color changes are definitely the perfect thing to get your feet wet though with CSS, using the [Tota11y](https://khan.github.io/tota11y/) toolbar (should you decide), using github, and maybe also using the built-in browser `Inspect Element`.

In terms of impact we would be able to declare we officially completely support color blindness (only leaving low vision, ambulatory, and blindness left to provide solutions for).

**Comment by bollwyvl** [comment]
we should just ship `tota11y` in core :duck:

**Comment by bollwyvl** [comment]
potentially related, at least in proposal rubrics:
- United Nateions [THE 17 GOALS](https://sdgs.un.org/goals)
  - [Goal 4: Quality Education](https://sdgs.un.org/goals/goal4)

**Comment by manfromjupyter** [comment]
> we should just ship `tota11y` in core 🦆
> 
> * 76kb: https://bundlephobia.com/result?p=@khanacademy/tota11y@0.2.0

Complete side note, just wanted to add, yes it could help us test things 20 seconds faster, but perhaps could allow people to review notebooks for accessibility before they ship/bundle them up for their coworkers, classes, etc (if there is a use case for that).

**Comment by tonyfast** [comment]
> allow people to review notebooks for accessibility before they ship/bundle them up for their coworkers, classes, etc (if there is a use case for that).

I <3 this a lot. currently, there is no idea of  caption for matplotlib images or alt text in svgs. 

there might be some upstream nbconvert changes we could make based on the nbformat that be expose a more accessible in the static renderings. 

we could also think about how the metadata could be used to define accessibility attributes. potentially you could edit roles/titles/aria directly in the metadata
