### ISSUE TITLE
Standardize accessibility text for output images

### ISSUE THREAD

**Issue by blois** [jupyter/accessibility#37]
From: https://github.com/ipython/ipython/pull/12864

Currently there's no mechanism for notebook authors to specify alt text for images- there is no data in the notebook format to capture this. I took a naive approach to expose a simple string similar to other image metadata but it sounds like more structure may be desired.

I'm wondering if this is something that the accessibility working group would be able to help shepherd?

**Comment by tonyfast** [comment]
This is great that this got merged. I hope some folks will be use out of it!
