### ISSUE TITLE
Plan for a community workshop for accessibility

### ISSUE THREAD

**Issue by choldgraf** [jupyter/accessibility#43]
# Background

In #11 we did some early planning and discussion around a workshop for accessibility in the Jupyter ecosystem. The basic plan was to bring together experts in accessibility, along with experts in the Jupyter ecosystem (in particular, JupyterLab most likely). The goal was to do a deep dive into the Jupyter architecture, understand the challenges we face, and create a roadmap of concrete steps to improve a11y in Jupyter. We also secured funding to host this workshop from the Bloomberg events fund.

Then we had a pandemic...😷

And now we are re-booting this process!

# Planning another a11y workshop

I spoke with @Ruv7 and she mentioned that the funds are still available for us to use any time **before the end of 2022**. So I have a few questions for folks:

- Do others still believe there is value in having a workshop to discuss and plan Jupyter and accessibility?
- We have made much progress in this space (in a big way to the leadership and energy of @isabela-pf and many others), has this work changed what kind of format we should use?
- Should a workshop still be fully in-person? (if so, we probably must wait until 2022) or can we do something that is a asynchronous + synchronous remote event (and use the funds to buy everybody high-quality microphones or something).
- Are others interested in helping to co-organize a workshop?

**Comment by isabela-pf** [comment]
Based on our accessibility meetings, I'm tagging @trallard and @tonyfast since we've all talked about being interested in workshop organizing.

**Comment by tonyfast** [comment]
> I spoke with @Ruv7 and she mentioned that the funds are still available for us to use any time **before the end of 2022**. So I have a few questions for folks:
> 
>     * Do others still believe there is value in having a workshop to discuss and plan Jupyter and accessibility?

there is definitely value in a workshop or workshp[s. 

>     * We have made much progress in this space (in a big way to the leadership and energy of @isabela-pf and many others), has this work changed what kind of format we should use?

i think whats different is we have a little more direction about what needs to get done to start involving testers and developers.

>     * Should a workshop still be fully in-person? (if so, we probably must wait until 2022) or can we do something that is a asynchronous + synchronous remote event (and use the funds to buy everybody high-quality microphones or something).

i don't think an in person accessibility community event is responsible in 2021, and if we wait til 2022 then we are waiting delaying our impact in accessibility. i'd personally like to see if we can stretch the money out over a few events or pair mentoring sessions; the multiple events would help us build and reinforce community. 

are there limits on the use of funds? would it be possible to use the funds to purchase folks food or a meal ordering service, or send out swag or something specific to the event?

**Comment by choldgraf** [comment]
My feeling is that they are pretty flexible on what exactly we use the money for, so long as we spend it by 2022. We could certainly use it to buy food for people, or goodies such as nice microphones etc. IMO anything that would result in a more productive event would be in-scope for the budget (so long as we don't go over the original budget)

I am not sure how they feel about using multiple, smaller events rather than one big one, but TBH I think that could be a much more natural use of these resources than forcing it to be "a single event", particularly if it will be distributed. Let me ask and get back to y'all

**Comment by trallard** [comment]
Definitely online! I am still not hopeful that we will be able to meet in person any time soon.

> We could certainly use it to buy food for people, or goodies such as nice microphones etc. IMO anything that would result in a more productive event would be in-scope for the budget (so long as we don't go over the original budget)

A microphone would be good - Having a virtual dinner and pay for that would be good, I do miss those opportunities to mingle with folks and get to know them better.

**Comment by tonyfast** [comment]
something came to mind over the weekend. maybe we could use funds to pay for accessibility training from [deque](https://www.deque.com/). this could have an impact for the larger development community.

**Comment by choldgraf** [comment]
I heard back from the team coordinating these events, and they said it'd be totally fine to break it up into a few smaller workshops rather than one big one. I also like @tonyfast's idea - I wonder if we could do something like host 2-3 focused working sessions, and 1-2 "accessibility training sessions" for the Jupyter community.

Or more generally - I believe that @isabela-pf and the `jupyter/accessibility` team have the best visibility onto what would make the most impact. What advise would you have for how to best use these resources?

**Comment by trallard** [comment]
Thanks for the update @choldgraf  I definitely like the idea of hands on + workshop. 

Will leave it to Isabela to follow through with the a11y team and report back.

**Comment by isabela-pf** [comment]
Just added it to the agenda for next Wednesday's accessibility meeting. I have some thoughts, but I want to make space for the team to get more involved. More to come then!

**Comment by tonyfast** [comment]
I propose the following 3/4 rounds of events with the following format that we can tweak with time. I think we should shoot for July for the first event and each event would be on a saturday at that sweet spot time when the US and EU are awake.

# round format

each round is a pair of events than can be run every 2/3 months (3/4x with our budget). there are two events per round:
1.  entertaining group learning experience about accessibility and disability

  * :00-:10 Folks arrive
  * :10-:15 goal settings for event
  * :15-:25 an icebreaker to introduce attendees to each other
  * :25-:40 update of jupyterlab accessibility(15min)    
  * :40-1:40 main speaker (1 hour)
     we'll use funds to pay for presentations from well known accessibility experts like: https://twitter.com/karlgroves, https://twitter.com/annaecook, https://twitter.com/AshleeMBoyer, https://twitter.com/kiran_oliver
  * 1:50-2:45 of breakout out group discussion (x2)
  * 2:45-3:00 wrap up (preparation for mentored sprints)
  * 3:00-4:00 (optional) setting up an development environment

2. mentored sprints (1/2) week(s) following

we'll use funding to buy folks food through doordash or whatever we can use.

i'm happy do a lot of the :leg: work (eg speaker fees) to get these events organized and mediated.

**Comment by isabela-pf** [comment]
Following up on @tonyfast's above comment, I'm interested in having action-focused events too. Following his numbering

2. mentored sprint ideas

Documentation-focused sprint. I think being able to write about something makes you learn it well, so I see this as a good chance to have participants learn and help the community at the same time (and is much more scoped than solving all a project’s problems). Here are a few ideas:
- Alt text sprint! Teach people how to write alt text then fill in missing alt text across the docs.
- Update contributing guide to include accessibility as a part of the expected workflow. This may include coming up with the recommendations.
- Sprint on the accessibility of the docs theme. I don’t have as much info about this, but there are leads I can chase down if we are interested.

I’m hesitant to set goals for specific projects without more work scoping that. I’ve had too many times on JupyterLab thinking an issue was straightforward and isolated only to have it end up the opposite and I think events like this are about creating forward momentum. Still, I have some very scoped ideas:
- CSS-only changes needed
- Labeling and tagging

**Comment by artificialsoph** [comment]
Hi all, just wanted to tag in to say that I'm interested in pitching in on this event. Specifically I would love to help lead one or more mentored sprints (I love @isabela-pf 's suggestions)

**Comment by choldgraf** [comment]
Hey all - a couple quick thoughts:

- I like the format that @tonyfast describes. One tweak I might suggest is to have the presentations themselves pre-recorded if possible, and using the meeting time for discussion and digging into specific topics. This would both make the event more accessible to non-attendees, and would take advantage of everybody's synchronous attention.
- The major goal of the original proposal for these events was to get a11y experts in the same room with JupyterLab (and broader Jupyter ecosystem) experts so that we could answer ally questions much faster than we could separately. I think an important task for these events will be *wrangling* people to make sure that the right folks are in the room for discussions. This might be easier if each event was scoped to a particular use-case or part of the stack, so others knew when / if to join in.

More generally, I appreciate the energy that you're all bringing to this discussion. Is anybody from this group interested in co-administering the funding from NumFocus? I don't think I should be a bottleneck for deciding how to use the funding, I think you all have much better vision for this than I do!

**Comment by trallard** [comment]
I just had a chat with Isabela about this and we both are happy to help unblock stuff - if you need someone in name for funding feel free to put me down @choldgraf

**Comment by choldgraf** [comment]
@trallard ill cc you on an email with the numfocus folks this week 👍

**Comment by isabela-pf** [comment]
As @choldgraf reminded above, the main goal of the proposal was to connect accessibility experts with Jupyter community members. If we start reaching out to accessibility experts, it sounds to me like we could start scheduling events. Does that sound reasonable to y'all?

**Comment by tonyfast** [comment]
i think at this point planning an event async is going to be challenge. it would probably be good to have a recurring meeting to stay up on this otherwise I'm afraid it will get lost in the shuffle or get insufficient attention.

**Comment by isabela-pf** [comment]
## Notes from 7-1-2021
### (Tony and Isabela)
-

**Comment by isabela-pf** [comment]
Related to the above comment, here's the current version of an outreach template. Thoughts? https://github.com/Quansight-Labs/jupyter-accessibility-workshops/blob/main/docs/outreach-template.md

**Comment by tonyfast** [comment]
@isabela-pf can you update some of these checklists if they are done?

we know have dates now:
1. September 18, 2021 for the community knowledge sharing event
2. September 25, 2021 for the community sprint

folks are encouragement to participate in either event for as long as they feel comfortable.

questions:
* what time should we start? 8 am pst too early?
* would different times for each event make it possible to access others?

**Comment by tonyfast** [comment]
> * [ ]  contact accessibility experts

in progress

> * [ ]  choose platform(s) for the event

we chose the project jupyter zoom at the main rally point
   
>   * [ ]  one repository for both experiences

i think there is a repo

>   * [ ]  consider disability from all perspectives

all this needs discussion and budgetting.
     
>   * [ ]  a disclaimer that disabled people won't be able to experience jupyter

are there any docs in jupyter specifically about accessibility or compliance. even if it is :( we'd have a document to start editting.

> * [ ]  code of conduct

i'm sure @isabela-pf has a deck of these

> * [ ]  decide on dates

9/18/2021 - 9/25/2021

> * [ ]  decide on times

in progress

> * [ ]  forms

in progress

**Comment by isabela-pf** [comment]
> what time should we start? 8 am pst too early?

While I find that people in PST often thing 8am PST is too early, I think it works well for a lot of the other timezones I know we have in the community and would like to include.

**Comment by trallard** [comment]
9-10 am PDT is still EMEA friendly

**Comment by isabela-pf** [comment]
Hi there! I realized I haven't updated this in a while because I've been working on the [workshop repo](https://github.com/Quansight-Labs/jupyter-accessibility-workshops) and [the repo's projects](https://github.com/Quansight-Labs/jupyter-accessibility-workshops/projects) being used as a kind of per-event to do list.

- Updated dates for the first set of events: October 2 and October 9. 
- We still haven't scheduled a time of day, but it sounds like starting at 8 or 9 am PDT will work for a few time zones.
-  First event is speaker and discussion focused, second is a mini sprint around documentation

Are there any other questions I can answer for you all.

**Comment by isabela-pf** [comment]
More updates! We have budget approval, which means the dates are also set. Yay!!!

I'm currently working on getting everything together to announce these events with sign-up info.

@choldgraf do you know what the process is/where to reach out to for review on a draft blog post for the Jupyter blog? I found the [Jupyter blog post contribution guide](https://jupyter.readthedocs.io/en/latest/contributing/communication-contributions.html), but I don't see exactly where I'm supposed to contact.

**Comment by choldgraf** [comment]
I believe that those documentation are out of date unfortunately. In practice, our blog has been following a similar practice as our repositories: somebody posts a draft, finds a reviewer, and generally after a review we post it if all parties are happy. I don't think it's a good process from an organizational comms strategy standpoint, but it's the one we have for now :-)

I am happy to be a reviewer for this blog post if you'd like to point me in the right direction!

**Comment by isabela-pf** [comment]
Thanks for offering to give it a review! The [draft blog post is a PR on the workshop planning repo](https://github.com/Quansight-Labs/jupyter-accessibility-workshops/pull/8) for now. Feel free to leave any comments.

> I would also be happy to do a quick docs update with you to update that content and make it more accurate. What do you think?

Updating docs always sounds good to me. If you know what content needs to be there, I'm happy to do my best to put in a PR.

**Comment by tonyfast** [comment]
The first round of events are through, and the next series of events is in the work. I think that is good reason to close this issue. Thanks @choldgraf @trallard @isabela-pf for making these critical events happen.
