### ISSUE TITLE
Notebook extension for dyslexic and visual accessibility

### ISSUE THREAD

**Issue by joshuazeltser** [jupyter/accessibility#5]
We are a team of MSc students from UCL working on the accessibility of Jupyter Notebooks. We are looking at creating some extensions which focus on accessibility for people with dyslexia or colour blindness. We are thinking of working on the following five extensions:

Text format toolbar - A toolbar which allows users to change the text size, colour, spacing etc. to make the text as readable/accessible as possible for users
Code spell checker - Live syntax checking of code as the user types underlining when a syntax error has occurred
Voice control - Allow some commonly used functionality such as running a notebook, restarting the kernel etc. be carried out using voice control
Planner - a planner that is displayed down the side of a page allowing the user to plan out and write notes about their notebook
Accessible themes - various themes such as high contrast which will make the notebook more easily readable
It would be great if anyone could give us some feedback about these ideas and whether they are feasible.

**Comment by fperez** [comment]
Thanks @joshuazeltser for posting here, this will be a good place to gather a11y-related discussions.

I wanted to point to you and anyone else coming by that we now also have a proper [accessibility category on our Discourse](https://discourse.jupyter.org/c/special-topics/accessibility), and I would encourage you to be active there as well!  Bootstrapping a communications space can be a bit slow at the start, so don't be surprised if the conversation doesn't pick up in earnest right away :)  But hopefully with multiple people interested in this pitching in, we can build up critical mass...

**Comment by fperez** [comment]
As for the specifics of your questions above - the first question to clarify is whether you're thinking of Classic Notebook or JupyterLab? With JLab hitting 1.0rc a few days ago (and thus proper 1.0 status soon, hopefully in very few weeks), we'd like to focus development efforts there. It's designed for extensibility from the get-go, so add-on tools will hopefully fit more cleanly than they did in the classic architecture.

Accessible themes might be a nice one to start with - JLab already has theming support, so this one is likely to be one of the least intrusive...
