### ISSUE TITLE
Logo for Jupyter a11y

### ISSUE THREAD

**Issue by telamonian** [jupyter/accessibility#54]
As part of a scipy talk, i made a logo for the a11y work:

![image](https://user-images.githubusercontent.com/2263641/125968475-6d1ed3e0-9888-4361-a160-f8db6d658213.png)

I think it looks pretty good. If people like it, I'll upload some logo assets to this repo

**Comment by telamonian** [comment]
Here's the svg for the high qual version, so i don't lose track of it:

```svg
<svg width="40" height="51" viewBox="0 0 40 51" xmlns="http://www.w3.org/2000/svg">
  <g class="jp-icon-warn0" fill="#F37726">
    <path transform="translate(1.74 30.98)" d="M 18.2646 7.13411C 10.4145 7.13411 3.55872 4.2576 0 0C 1.32539 3.8204 3.79556 7.13081 7.0686 9.47303C 10.3417 11.8152 14.2557 13.0734 18.269 13.0734C 22.2823 13.0734 26.1963 11.8152 29.4694 9.47303C 32.7424 7.13081 35.2126 3.8204 36.538 0C 32.9705 4.2576 26.1148 7.13411 18.2646 7.13411Z"/>
    <path transform="translate(1.73 4.48)" d="M 18.2733 5.93931C 26.1235 5.93931 32.9793 8.81583 36.538 13.0734C 35.2126 9.25303 32.7424 5.94262 29.4694 3.6004C 26.1963 1.25818 22.2823 0 18.269 0C 14.2557 0 10.3417 1.25818 7.0686 3.6004C 3.79556 5.94262 1.32539 9.25303 0 13.0734C 3.56745 8.82463 10.4232 5.93931 18.2733 5.93931Z"/>
  </g>
  <g class="jp-icon3" fill="#616161">
    <path transform="translate(31.3 0.31)" d="M 5.89353 2.844C 5.91889 3.43165 5.77085 4.01367 5.46815 4.51645C 5.16545 5.01922 4.72168 5.42015 4.19299 5.66851C 3.6643 5.91688 3.07444 6.00151 2.49805 5.91171C 1.92166 5.8219 1.38463 5.5617 0.954898 5.16401C 0.52517 4.76633 0.222056 4.24903 0.0839037 3.67757C -0.0542483 3.10611 -0.02123 2.50617 0.178781 1.95364C 0.378793 1.4011 0.736809 0.920817 1.20754 0.573538C 1.67826 0.226259 2.24055 0.0275919 2.82326 0.00267229C 3.60389 -0.0307115 4.36573 0.249789 4.94142 0.782551C 5.51711 1.31531 5.85956 2.05676 5.89353 2.844Z"/>
    <path transform="translate(1.8 42.81)" d="M 7.42789 3.58338C 7.46008 4.3243 7.27355 5.05819 6.89193 5.69213C 6.51031 6.32607 5.95075 6.83156 5.28411 7.1446C 4.61747 7.45763 3.87371 7.56414 3.14702 7.45063C 2.42032 7.33712 1.74336 7.0087 1.20184 6.50695C 0.660328 6.0052 0.27861 5.35268 0.105017 4.63202C -0.0685757 3.91135 -0.0262361 3.15494 0.226675 2.45856C 0.479587 1.76217 0.931697 1.15713 1.52576 0.720033C 2.11983 0.282935 2.82914 0.0334395 3.56389 0.00313344C 4.54667 -0.0374033 5.50529 0.316706 6.22961 0.987835C 6.95393 1.65896 7.38484 2.59235 7.42789 3.58338L 7.42789 3.58338Z"/>
    <path transform="translate(0.36 5.06)" d="M 2.27471 4.39629C 1.84363 4.41508 1.41671 4.30445 1.04799 4.07843C 0.679268 3.8524 0.385328 3.52114 0.203371 3.12656C 0.0214136 2.73198 -0.0403798 2.29183 0.0258116 1.86181C 0.0920031 1.4318 0.283204 1.03126 0.575213 0.710883C 0.867222 0.39051 1.24691 0.164708 1.66622 0.0620592C 2.08553 -0.0405897 2.52561 -0.0154714 2.93076 0.134235C 3.33591 0.283941 3.68792 0.551505 3.94222 0.90306C 4.19652 1.25462 4.34169 1.67436 4.35935 2.10916C 4.38299 2.69107 4.17678 3.25869 3.78597 3.68746C 3.39516 4.11624 2.85166 4.37116 2.27471 4.39629L 2.27471 4.39629Z"/>
  </g>
  <g class="jp-icon3" fill="#616161">
    <text x="0" y="29" font-family="Myriad Pro" font-weight="bold" font-size="18.5">
      a11y
    </text>
  </g>
</svg>

```

I'll turn this into some assets and upload them in a PR later

**Comment by SylvainCorlay** [comment]
Arg, unfortunately, we may have to check the Jupyter logo usage guidelines. I don't think it is ok to make modifications to the original logo.

**Comment by slel** [comment]
Indeed the trademark guidelines seem to forbid altering the logo:

- https://jupyter.org/governance/trademarks.html

**Comment by choldgraf** [comment]
Could you try extending the rectangular logo like in the community forum? https://discourse.jupyter.org/

**Comment by telamonian** [comment]
Here's the [relevant section](https://jupyter.org/governance/trademarks.html#uses-that-always-require-approval) from the trademark guidelines:

> Uses that Always Require Approval
>
> ...
>
> Any use of a derived (modified) logo for any commercial or non-commercial purpose must also be approved first by Project Jupyter. We will generally be unable to do this because of the confusion it may cause.

So logo variants are allowable, but they require approval by the [Jupyter Trademarks Comittee](jupyter-trademarks@googlegroups.com). Not quite sure who's sitting on that comittee, but I'll write them an email

**Comment by telamonian** [comment]
There are at least a few extant examples of text fill variants of our "RindMoon" logo:

![image](https://user-images.githubusercontent.com/2263641/130357005-0fead86d-abc6-4962-9a7d-f68aba7bfd5f.png)

![image](https://user-images.githubusercontent.com/2263641/130357024-58ac3162-eef6-423a-a715-17514a5d1dc7.png)

**Comment by sabderemane** [comment]
I don't know if it is following all the rules of the guidelines and if the subject is still relevant now but I have done [a logo](https://github.com/jupyter/accessibility/blob/master/docs/source/_static/logo.png)
 when I create the RTD documentation.

**Comment by trallard** [comment]
Thanks for surfacing this @sabderemane - I believe the logo you pointed to aligns with the guidelines (since we already have another example of such use as pointed out by Chris in https://discourse.jupyter.org/)

An open question for the rest of the folks: can we use the above logo for a11y -related stuff moving forward?

**Comment by choldgraf** [comment]
@sabderemane I think that's a nice re-use of the main logo, and it follows similar patterns that other projects have followed as well! I agree with @trallard's assessment, but do recognize that we don't have an official policy for this

**Comment by trallard** [comment]
Do we need to do anything else here? The logo is now in the repo and in use

**Comment by trallard** [comment]
Before I close @sabderemane so you have the logo in svg? I think it would be useful for digital use cases

**Comment by sabderemane** [comment]
Of course @trallard, here it is :
![jupyter-a11y-logo](https://user-images.githubusercontent.com/17890338/169514490-344eeecb-a9ed-4ee2-92f1-e8a57f040b8c.svg)
Don't hesitate to contact me if you need anything else.

**Comment by trallard** [comment]
Thank you so much - will add it to the repo
