### ISSUE TITLE
Formalizing the structure for this repo

### ISSUE THREAD

**Issue by tonyfast** [jupyter/accessibility#67]
We're going to restructure the project to contain multiple things. The list below highlights some of the larger things we hope to achieve.

- typescript packages that use jupyterlab/lumino/retrolab to extend accessibility features like automated testing and remediations

  we start with a multi package layout ala retrolab

- a python project with tasks for managing file system tasks with `doit`
   
   noxfile and dodo will move into the package called `ja11y`

- documentation about jupyter and its accessibility (move sphinx to jupyter book)
  - past audits (eg https://github.com/jupyter/accessibility/issues/7)
  - contributing guidelines https://github.com/jupyter/accessibility/issues/47
  - research
  - resources/tools/best practices https://github.com/jupyter/accessibility/issues/15
  - Meeting Information/Minutes
  - Jupyter Accessibility Statement
- add continuous integrations (documentation, binder building)

## specifics

below is a checklist of things that will be included before or during the transition.

- [x] #39 
- [x] #21
- [ ] #35 
- [ ] #66 
- [ ] #64

**Comment by trallard** [comment]
Marking this on hold due to #86
