### ISSUE TITLE
Definiting a jupyter accessibility statement

### ISSUE THREAD

**Issue by tonyfast** [jupyter/accessibility#72]
#71 introduces a page for jupyter's accessibility statement in (STATEMENT.md). currently there is a placeholder, but a formal description will be needed.

@isabela-pf do you some ideas about how we'll format this statement? are there any good examples you've found?

**Comment by isabela-pf** [comment]
Short answer: I have no idea what goes in a accessibility statement off the top of my head! 

Happy to explore some options though. I have a feeling a key part will be the "no, the software is not currently accessible" statement on the readme right now.

**Comment by tonyfast** [comment]
looks like the w3c can generate one for us https://www.w3.org/WAI/planning/statements/generator/#create

**Comment by isabela-pf** [comment]
This was a really good find. Thanks for sharing @tonyfast!

I see you have some [accessibility statements linked in the documentation site](https://jupyter-accessibility.readthedocs.io/en/restructure/docs/statement.html), but they seem different than the template you shared. When would it be appropriate to consider this issue resolved? When we have statements on this repo/the documentation website? Or also on individual projects with user-facing interfaces?
